gopher market server v.0.1
zvfkjytytw/gophmarkt pull request #1
Opened 2024-07-30 12:48 UTC by zvfkjytytw

Without accrual system

2024-08-12 19:59 UTC, avhitrov requested changes
Замечания по организации работы с системой accrual и с БД. Все в комментариях к коду, часть замечаний касается серийных проблем (row.Scan)

2024-08-12 19:59 UTC, avhitrov commented on build/migrations/1_init_db.up.sql
> +CREATE UNIQUE INDEX idx_gophmarkt_users ON gophmarkt.users (login);
PRIMARY KEY и так обладает свойством уникальности. Нет необходимости объявлять еще один индекс.

2024-08-12 19:59 UTC, avhitrov commented on build/migrations/1_init_db.up.sql
> +ALTER TABLE gophmarkt.balance ADD PRIMARY KEY (login);
А вот здесь лучше объявить FOREIGN KEY и сделать его уникальным

2024-08-12 19:59 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	stop    chan struct{}
wg sync.WaitGroup

2024-08-12 19:59 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +func (a *Accrual) Start(ctx context.Context) error {
```
a.wg.Add(1)
defer a.wg.Done()
```

2024-08-12 19:59 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	close(a.stop)
```
a.wg.Wait()
```
Иначе после закрытия соединения можем словить панику, если checkOrders() будет еще молотить. Можно обойтись без WaitGroup, если вместо закрытия канала сделать:
```
stop <- struct{}{}
```

2024-08-12 19:59 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	for _, order := range orders {
При такой организации можно легко и быстро зафлудить систему accrual. Достаточно взять чанк в 1000 записей - и где-то 900 из них, скорее всего, словят 429 ошибку. Архитектурно надо:
- либо делать в один поток, и тогда достаточно просто следить за получением 429 кода;
- делать пул воркеров, в этом случае необходимо будет добавить общее поле (time.Time), по которому синхронизировать работу воркеров при получении TooManyRequests. С блокировкой, естественно.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	}
Нет проверки на статус ответа. Весь анмаршалинг уместен только для HttpOK. В остальных случаях необходимо либо выходить с ошибкой, либо, в случае получения 429, замирать (причем сразу всем воркерам) и перезапрашивать по истечении времени, указанном в заголовке.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	if row.Scan(&own) != sql.ErrNoRows {
Слишком беспечная проверка. Под капотом у row.Scan довольно много ошибок, не только `sql.ErrNoRows`, при этом все возникшие ошибки нельзя трактовать ни как `order already upload`, ни как `order upload by other`.

Документация и код (https://cs.opensource.google/go/go/+/refs/tags/go1.22.6:src/database/sql/sql.go;l=3442) рекомендуют при использовании QueryRow и QueryRowContext ошибки ловить на row.Scan и не раньше.

Это касается **всех** случаев использования QueryRow в данном коде.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	tx, err := s.db.Begin()
Ради одной SQL-операции нет смысла открывать транзакцию. Один запрос и так транзакционно безопасен.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	if row.Scan(&status, &login) == sql.ErrNoRows {
row.Scan рождает ошибки, которые не только ErrNoRows. При возникновении любой из них status и login будут невалидны.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	}
```
defer tx.Rollback()
```
и можно не париться с вызовом этой процедуры перед каждым `return err`

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_withdrawals.go
> +	query, args, err = sq.Select("current", "withdrawn").From(balanceTable).Where(sq.Eq{"login": login}).PlaceholderFormat(sq.Dollar).ToSql()
Чтобы SELECT попал в транзакцию, его необходимо пометить, как `FOR UPDATE`.
https://t.me/bushigo/36

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	}
Эта проверка недостаточна, так как не охватывает все случаи возникновения ошибок при организации запроса и сканировании. Более компетентная ошибка возникает только при row.Scan. Этот комментарий касается всех случаев применения в данном коде.

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +	row := s.db.QueryRow(query, args...)
```suggestion
	row := s.db.QueryRowContext(ctx, query, args...)
```

2024-08-12 19:59 UTC, avhitrov commented on internal/server/storage/pg_orders.go
> +func (s *PGStorage) AddOrder(oid, login string) (OrderOperationResult, error) {
```suggestion
func (s *PGStorage) AddOrder(ctx context.Context, oid, login string) (OrderOperationResult, error) {
```

2024-08-20 15:21 UTC, zvfkjytytw commented on internal/server/storage/pg_orders.go
> +	}
добавил проверок на все сканирования

2024-08-20 15:21 UTC, zvfkjytytw commented on internal/server/storage/pg_orders.go
> +	row := s.db.QueryRow(query, args...)
переделал все запросы к базе на запросы с контекстом

2024-08-20 15:22 UTC, zvfkjytytw commented on internal/server/storage/pg_orders.go
> +func (s *PGStorage) AddOrder(oid, login string) (OrderOperationResult, error) {
переделал все запросы к базе на запросы с контекстом

2024-08-20 15:22 UTC, zvfkjytytw commented on internal/server/storage/pg_withdrawals.go
> +	query, args, err = sq.Select("current", "withdrawn").From(balanceTable).Where(sq.Eq{"login": login}).PlaceholderFormat(sq.Dollar).ToSql()
добавил суфикс "FOR UPDATE" к таким запросам

2024-08-20 15:23 UTC, zvfkjytytw commented on internal/server/storage/pg_orders.go
> +	}
везде вывед tx.Rollback в defer

2024-08-20 15:24 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +	close(a.stop)
добавил WaitGroup в структуру Accrual и обновление статусов заказов через неё

2024-08-20 15:25 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +func (a *Accrual) Start(ctx context.Context) error {
добавил WaitGroup

2024-08-20 15:25 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +	stop    chan struct{}
добавил WaitGroup

2024-08-20 15:26 UTC, zvfkjytytw commented on build/migrations/1_init_db.up.sql
> +ALTER TABLE gophmarkt.balance ADD PRIMARY KEY (login);
Изменил на Foreign Key

2024-08-20 15:28 UTC, zvfkjytytw commented on build/migrations/1_init_db.up.sql
> +CREATE UNIQUE INDEX idx_gophmarkt_users ON gophmarkt.users (login);
Индексы подразумевались для ускорения поиска по таблицам users  и balance. В таблицах orders и withdrawals постоянные добавления и индекс там будет только мешать, имхо.
Убрал индексы

2024-09-03 23:09 UTC, avhitrov requested changes
Необходимо допилить систему проверки статусов:
1. Реакцию на 429 ошибку
2. Сделать Stop() блокирующей (WaitGroup или блокирующая запись в канал stop)

2024-09-03 23:09 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	for _, order := range orders {
Я все равно не вижу логики, связанной с обработкой TooManyRequests (429). Предлагаю все-таки сделать обработчик однопоточным и при получении ошибки "замирать" на переданное в заголовке количество секунд. В этом случае отпадет необходимость использования WaitGroup в данной функции.

2024-09-03 23:09 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	close(a.stop)
Не вполне понят смысл использования WaitGroup в данном пакете. Группа ожидания здесь нужна в первую очередь для того, чтобы при окончании работы программы дождаться завершения полного цикла проверки (либо безопасно прервать и все равно дождаться). Соответственно, необходимо сделать функцию Stop() блокирующей (одним из описанных мной способов). А поскольку в цикл обработки проброшен контекст приложения, то его состояние вполне можно проверять в checkOrders в цикле `for _, order := range orders {` перед каждой проверкой загруженного заказа. Например так:
```
for _, order := range orders {
    if ctx.Err() != nil {
        return
    }
```

2024-09-13 03:20 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +	for _, order := range orders {
Добавил логики

2024-09-13 03:25 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +	close(a.stop)
Добавил

2024-09-17 22:19 UTC, avhitrov requested changes
Остались вопросы по взаимодействию с accrual-системой. Предлагаю взять 1-1

2024-09-17 22:19 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +var tooManyRequests error
```suggestion
var tooManyRequests = errors.New("Too many requests")
```

2024-09-17 22:19 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +				*enough = true
Это почти гарантированно DATA RACE. Чтобы избежать гонок, необходимо использовать `atomic.Bool`.

2024-09-17 22:19 UTC, avhitrov commented on internal/server/accrual/accrual.go
> +	for _, order := range orders {
Добавленная логика, если что и решает, так только добавляет пустых телодвижений подсистеме работы с БД. Без фиксации значения, пришедшего от accrual-системы в заголовке и установки паузы на это время мы будем выкачивать из БД, долбиться в сервис, получать отлуп, сбрасывать батч и снова долбиться. Если реализация данной части кода вызывает непонимание, предлагаю взять 1-1 и подробно обсудить реализацию и корнер -кейсы.

2024-09-20 00:52 UTC, zvfkjytytw commented on internal/server/accrual/accrual.go
> +				*enough = true
Переделал на последовательную обработку запросов, с паузой между запросами и выходом при TooManyRequests.

2024-09-24 22:18 UTC, avhitrov approved these changes
Ок, думаю, по сумме доработок код вполне можно принять. Поздравляю с первым дипломом!

2024-09-27 05:23 UTC, merged